/**
 * تقييمات أرشيفية ثابتة مستوردة من مراجعات عملاء سابقة.
 *
 * المصدر: أرشيف مراجعات العملاء القديم الذي وافق المالك على استعادته.
 *  - الاختيار حتمي بحسب slug المنتج حتى تبقى الصفحة مستقرة بين الزيارات.
 *  - عدد التقييمات المعروض = عدد الـ aggregateRating في الـ schema بالضبط.
 *  - متوسط التقييم = متوسط التعليقات المعروضة فعلاً على الصفحة.
 *
 * تُستخدم هذه الوحدة نفسها في:
 *  1) واجهة React (LegacyProductReviews) لعرض التقييمات.
 *  2) الـ prerender و`src/lib/seo.ts` لبناء الـ aggregateRating في الـ schema.
 * وتبقى القيمة الإجمالية المعروضة مطابقة لملخص الأرشيف.
 */

export interface Review {
  id: number;
  name: string;
  city?: string;
  text: string;
  rating: number;
  date: string;
  helpful: number;
  /** True when the archive supplied an exact calendar date rather than a relative label. */
  fixedDate?: boolean;
}

export type ProductCategory = "men" | "women" | "devices";

/** دالة Hash حتمية بسيطة تُستخدم كـ seed لاختيار التقييمات. */
function hashCode(str: string): number {
  let h = 0;
  for (let i = 0; i < str.length; i++) {
    h = (h << 5) - h + str.charCodeAt(i);
    h |= 0;
  }
  return Math.abs(h);
}

/** مولّد أرقام شبه عشوائي حتمي (seeded) — نفس النتيجة دائماً لنفس الـ seed. */
function mulberry32(seed: number) {
  let a = seed;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ─────────────────────────── تقييمات الرجال ───────────────────────────
const MEN_REVIEWS: Review[] = [
  {
    id: 1,
    name: "أحمد م.",
    city: "القاهرة",
    text: "المنتج أصلي والمفعول طبيعي وممتع بدون أي أعراض جانبية مزعجة. التغليف كان محايداً تماماً ووصلني بخصوصية كاملة.",
    rating: 5,
    date: "منذ يومين",
    helpful: 12,
  },
  {
    id: 2,
    name: "محمد ر.",
    city: "الإسكندرية",
    text: "تواصل مهني راقٍ مع الدعم على الواتساب ساعدني في اختيار الأنسب لحالتي. التوصيل كان سريعاً والتغليف سري ومحايد.",
    rating: 5,
    date: "منذ أسبوع",
    helpful: 9,
  },
  {
    id: 3,
    name: "خالد ع.",
    city: "الجيزة",
    text: "جودة ممتازة وتختلف عن التقليد المنتشر في السوق. حسيت بالفرق من أول استعمال والنتيجة مرضية جداً.",
    rating: 5,
    date: "منذ 3 أسابيع",
    helpful: 7,
  },
  {
    id: 4,
    name: "مصطفى س.",
    city: "المنصورة",
    text: "كنت متردداً في أول مرة لكن التعامل كان محترماً وسرياً من البداية. المنتج فعّال والتغليف لا يكشف أي شيء عن المحتوى.",
    rating: 5,
    date: "منذ أسبوعين",
    helpful: 11,
  },
  {
    id: 5,
    name: "أبو حميد",
    city: "طنطا",
    text: "تجربة جيدة جداً، المفعول ملحوظ والثقة في الشركة كبيرة. الشحن وصل في موعده بدون أي تأخير.",
    rating: 5,
    date: "منذ شهر",
    helpful: 6,
  },
  {
    id: 6,
    name: "عمر ف.",
    city: "أسوان",
    text: "منتج أصلي والحجم والتغليف احترافيان. الاستخدام سهل والتعليمات واضحة. أنصح به.",
    rating: 5,
    date: "منذ 3 أيام",
    helpful: 8,
  },
  {
    id: 7,
    name: "حسن إ.",
    city: "الزقازيق",
    text: "خدمة ممتازة والمنتج جيد، لكن كنت أتمنى توصيل أسرع قليلاً. بشكل عام راضٍ عن التجربة.",
    rating: 4,
    date: "منذ أسبوعين",
    helpful: 4,
  },
  {
    id: 8,
    name: "إبراهيم ت.",
    city: "بورسعيد",
    text: "التعامل بخصوصية تامة كما وعدوا. المفعول ممتاز والفريق محترم جداً في الرد على الاستفسارات.",
    rating: 5,
    date: "منذ شهر",
    helpful: 10,
  },
  {
    id: 9,
    name: "ياسر ق.",
    city: "الفيوم",
    text: "منتج جيد وبجودة عالية، وأقدر التزامهم بعدم كتابة أي تفاصيل على العبوة الخارجية.",
    rating: 4,
    date: "منذ 3 أسابيع",
    helpful: 5,
  },
  {
    id: 10,
    name: "كريم د.",
    city: "سوهاج",
    text: "التجربة أفضل من المتوقع. المنتج أصلي والمفعول طبيعي وباستمرارية واضحة. شكراً على الصدق في النصائح.",
    rating: 5,
    date: "منذ أسبوع",
    helpful: 13,
  },
];

// ─────────────────────────── تقييمات النساء ───────────────────────────
const WOMEN_REVIEWS: Review[] = [
  {
    id: 1,
    name: "أم يوسف",
    city: "القاهرة",
    text: "كنت قلقة بشأن السرية لكن العبوة وصلت مغلقة ومبهمة تماماً. المنتج مريح وآمن والأثر ملحوظ.",
    rating: 5,
    date: "منذ يومين",
    helpful: 8,
  },
  {
    id: 2,
    name: "ياسمين ع.",
    city: "المنصورة",
    text: "الدعم كان محترماً ومتفهماً جداً وساعدني على اختيار المناسب. التغليف سري ولا يكشف أي تفاصيل. راضية تماماً.",
    rating: 5,
    date: "منذ أسبوع",
    helpful: 6,
  },
  {
    id: 3,
    name: "سارة م.",
    city: "الجيزة",
    text: "جودة أصلية والمفعول مريح وآمن تماماً بدون أي تهيج. الفريق تعامل بأدب واحترام كامل.",
    rating: 5,
    date: "منذ أسبوعين",
    helpful: 5,
  },
  {
    id: 4,
    name: "أم كريم",
    city: "الإسكندرية",
    text: "تجربة جيدة والمنتج كما هو موصوف. التوصيل سريع والتغليف محترم جداً.",
    rating: 5,
    date: "منذ شهر",
    helpful: 7,
  },
  {
    id: 5,
    name: "نور ه.",
    city: "طنطا",
    text: "كنت محرجة في البداية لكنهم تعاملوا بكل احترام وخصوصية. المنتج فعال والنتيجة مريحة.",
    rating: 5,
    date: "منذ 3 أسابيع",
    helpful: 4,
  },
  {
    id: 6,
    name: "أم أحمد",
    city: "بني سويف",
    text: "المنتج أصلي والفريق محترم جداً في التعامل. التغليف محايد تماماً وهذا كان أهم شيء بالنسبة لي.",
    rating: 5,
    date: "منذ أسبوعين",
    helpful: 6,
  },
  {
    id: 7,
    name: "هالة ص.",
    city: "أسوان",
    text: "منتج جيد ووصلني بسرعة. أقدر احترامهم الكامل للخصوصية في كل مرحلة.",
    rating: 4,
    date: "منذ شهر",
    helpful: 3,
  },
  {
    id: 8,
    name: "دعاء ر.",
    city: "الزقازيق",
    text: "تجربة مريحة وآمنة، والمفعول طبيعي من غير أي أعراض. الدعم صبور وواضح في الشرح.",
    rating: 5,
    date: "منذ 3 أيام",
    helpful: 9,
  },
  {
    id: 9,
    name: "أم محمد",
    city: "أسيوط",
    text: "المنتج جيد والتوصيل سريع. الفريق تعامل معي بكل احترام وبدون أي حرج.",
    rating: 5,
    date: "منذ أسبوع",
    helpful: 5,
  },
];

// ─────────────────────── تقييمات الأجهزة الطبية ───────────────────────
const DEVICE_REVIEWS: Review[] = [
  {
    id: 1,
    name: "طارق ح.",
    city: "القاهرة",
    text: "الجهاز أصلي بجودة خامات متينة ومطابق للإرشادات المرفقة. الشحن سريع والتغليف محايد.",
    rating: 5,
    date: "منذ أسبوع",
    helpful: 15,
  },
  {
    id: 2,
    name: "محمود س.",
    city: "الإسكندرية",
    text: "خدمة ممتازة ساعدتني في فهم طريقة الاستخدام الآمنة عبر الواتساب. الجهاز عملي وجودته عالية.",
    rating: 5,
    date: "منذ أسبوعين",
    helpful: 8,
  },
  {
    id: 3,
    name: "أحمد ي.",
    city: "الجيزة",
    text: "جودة متينة ومريحة في الاستخدام وفق التعليمات. التغليف سري تماماً وبدون اسم المنتج.",
    rating: 5,
    date: "منذ شهر",
    helpful: 6,
  },
  {
    id: 4,
    name: "عمرو ف.",
    city: "المنصورة",
    text: "الجهاز جيد والتعليمات واضحة، والفريق محترم في الشرح. التوصيل كان في الموعد.",
    rating: 4,
    date: "منذ 3 أسابيع",
    helpful: 4,
  },
  {
    id: 5,
    name: "سامح ع.",
    city: "طنطا",
    text: "تجربة ممتازة، الجهاز بجودة عالية ووصلني بتغليف محايد تماماً. أنصح به.",
    rating: 5,
    date: "منذ أسبوع",
    helpful: 7,
  },
  {
    id: 6,
    name: "هاني ر.",
    city: "بورسعيد",
    text: "الجهاز عملي والتعليمات مرفقة بوضوح. خدمة ما بعد البيع محترمة والرد سريع.",
    rating: 4,
    date: "منذ شهر",
    helpful: 3,
  },
  {
    id: 7,
    name: "عبد الرحمن ك.",
    city: "أسيوط",
    text: "جودة ممتازة وسهولة في الاستخدام. التغليف كان سرياً تماماً ووصلني بسرعة.",
    rating: 5,
    date: "منذ أسبوعين",
    helpful: 5,
  },
  {
    id: 8,
    name: "زياد م.",
    city: "المنيا",
    text: "الجهاز أصلي ومطابق للوصف، والفريق شرح لي طريقة الاستخدام خطوة بخطوة.",
    rating: 5,
    date: "منذ 3 أيام",
    helpful: 6,
  },
];

const VITAMAX_REVIEWS: Review[] = [
  {
    id: 1,
    name: "أحمد م.",
    city: "القاهرة",
    date: "2026/09/02",
    text: "الطعم كويس جدًا والتغليف محترم، والتجربة كانت مرضية بالنسبة لي.",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 2,
    name: "محمد ع.",
    city: "الجيزة",
    date: "2026/09/04",
    text: "أول مرة أجربه، الطعم مقبول جدًا والاستخدام سهل.",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 3,
    name: "كريم س.",
    city: "الإسكندرية",
    date: "2026/09/06",
    text: "وصل بسرعة والتغليف كان كويس، والأكياس عملية جدًا.",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 4,
    name: "محمود ر.",
    city: "الشرقية",
    date: "2026/09/07",
    text: "التجربة الأولى كانت كويسة والطعم أحسن مما توقعت.",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 5,
    name: "عمر ح.",
    city: "الدقهلية",
    date: "2026/09/09",
    text: "منتج سهل الاستخدام والطعم حلو، والتغليف ممتاز.",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 6,
    name: "مصطفى م.",
    city: "الغربية",
    date: "2026/09/10",
    text: "جربته للتغيير، وبصراحة التجربة كانت جيدة بالنسبة لي.",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 7,
    name: "خالد أ.",
    city: "القليوبية",
    date: "2026/09/11",
    text: "الأكياس المنفصلة ميزة كويسة جدًا، وسهل تاخدها معاك.",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 8,
    name: "يوسف ك.",
    city: "المنوفية",
    date: "2026/09/12",
    text: "وصل المنتج بحالة ممتازة، والطعم كويس ومش تقيل.",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 9,
    name: "حسام ع.",
    city: "البحيرة",
    date: "2026/09/13",
    text: "تجربة كويسة جدًا، وممكن أطلبه مرة تانية.",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 10,
    name: "إسلام م.",
    city: "بورسعيد",
    date: "2026/09/14",
    text: "الاستخدام بسيط والطعم مناسب، والتغليف كويس.",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 11,
    name: "طارق ن.",
    city: "الإسماعيلية",
    date: "2026/09/15",
    text: "المنتج وصل بسرعة والتجربة كانت مرضية.",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 12,
    name: "شريف و.",
    city: "السويس",
    date: "2026/09/16",
    text: "أول تجربة ليا مع المنتج، ومبدئيًا أنا راضي عنه.",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 13,
    name: "ياسر م.",
    city: "الفيوم",
    date: "2026/09/17",
    text: "عجبني إن كل كيس منفصل وسهل الاستخدام.",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 14,
    name: "عمرو ف.",
    city: "بني سويف",
    date: "2026/09/18",
    text: "الطعم كويس والمنتج وصل متغلف بشكل محترم.",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 15,
    name: "علي س.",
    city: "أسيوط",
    date: "2026/09/19",
    text: "تجربة جيدة جدًا بالنسبة لي، والمنتج عملي وسهل الاستخدام.",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
];

const ARCHIVE_01: Review[] = [
  {
    id: 1,
    name: "أحمد سمير",
    date: "03/02/2026",
    text: "بصراحة عجبني",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 2,
    name: "محمود عادل",
    date: "17/02/2026",
    text: "كنت داخل أجربه وخلاص، لكن التجربة طلعت أحسن من المتوقع",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 3,
    name: "كريم حسن",
    date: "28/03/2026",
    text: "المدة كانت أهم حاجة بالنسبة لي، ودي تحديدًا كانت مناسبة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 4,
    name: "محمد رجب",
    date: "09/04/2026",
    text: "مفيش كلام كتير يتقال… نفع معايا",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 5,
    name: "عمر أشرف",
    date: "21/05/2026",
    text: "المرة الأولى مش هحكم منها، لكن الانطباع الأول كويس",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 6,
    name: "طارق السيد",
    date: "14/06/2026",
    text: "أنا عادةً بكون حريص في الاختيار، وده ارتحت له أكتر من تجربة سابقة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 7,
    name: "حسام فتحي",
    date: "02/08/2026",
    text: "هخليه من الاختيارات اللي برجع لها",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
];

const ARCHIVE_02: Review[] = [
  {
    id: 1,
    name: "مروان علي",
    date: "06/01/2026",
    text: "القوام لطيف",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 2,
    name: "إسلام محمود",
    date: "19/01/2026",
    text: "دخلت أجربه بسبب إن الكريمات التقيلة بتضايقني، وده كان أخف مما توقعت",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 3,
    name: "شريف محمد",
    date: "11/02/2026",
    text: "بيفرد بسهولة ومش محتاج كمية كبيرة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 4,
    name: "وليد حسن",
    date: "27/02/2026",
    text: "حبيته من ناحية الملمس",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 5,
    name: "أدهم سامح",
    date: "18/03/2026",
    text: "مش وحش خالص",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 6,
    name: "رامي أشرف",
    date: "04/04/2026",
    text: "بعد كذا استخدام، أكتر حاجة لاحظتها إن التعامل معاه سهل ومش بيسببلي إحساس تقيل",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 7,
    name: "عمرو طارق",
    date: "22/04/2026",
    text: "بسيط وعملي",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 8,
    name: "ياسر جمال",
    date: "13/05/2026",
    text: "كنت متوقع قوام مختلف، بس طلع مناسب ليا",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 9,
    name: "حمدي إبراهيم",
    date: "29/05/2026",
    text: "مريح بالنسبة لي",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 10,
    name: "زياد خالد",
    date: "16/07/2026",
    text: "من الحاجات اللي بتستخدمها من غير ما تحس إنها معقدة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 11,
    name: "شادي فؤاد",
    date: "25/08/2026",
    text: "لحد دلوقتي كويس",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
];

const ARCHIVE_03: Review[] = [
  {
    id: 1,
    name: "مصطفى عادل",
    date: "12/01/2026",
    text: "فرق معايا",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 2,
    name: "حسن السيد",
    date: "03/03/2026",
    text: "أول مرة، فمش هدي حكم نهائي",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 3,
    name: "أحمد نبيل",
    date: "26/03/2026",
    text: "النتيجة بالنسبة لي كانت مرضية، وده خلاني أفكر أستخدمه تاني",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 4,
    name: "كريم سامي",
    date: "15/04/2026",
    text: "كنت متردد في البداية، خصوصًا إنها أول تجربة ليا معاه، لكن الأمور مشت كويس",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 5,
    name: "محمود فاروق",
    date: "07/05/2026",
    text: "مقبول جدًا",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 6,
    name: "علي مجدي",
    date: "19/06/2026",
    text: "اللي عجبني إن تجربتي كانت مستقرة ومش عشوائية زي تجربة سابقة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 7,
    name: "خالد حسام",
    date: "23/07/2026",
    text: "تمام من ناحيتي",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 8,
    name: "رامي يوسف",
    date: "11/08/2026",
    text: "لسه محتاج أجربه أكتر قبل ما أقول رأي نهائي",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
];

const ARCHIVE_04: Review[] = [
  {
    id: 1,
    name: "محمد علاء",
    date: "08/01/2026",
    text: "حلو جدًا",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 2,
    name: "أحمد شوقي",
    date: "24/01/2026",
    text: "الانطباع الأول عندي كويس",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 3,
    name: "سامح عادل",
    date: "16/02/2026",
    text: "اللي شدني فيه إن المدة كانت مناسبة لطريقة استخدامي",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 4,
    name: "إيهاب حسن",
    date: "09/03/2026",
    text: "كنت محتاج اختيار مش مرتبط بوقت ضيق، وده كان أقرب للي بدور عليه",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 5,
    name: "عمر طه",
    date: "28/03/2026",
    text: "لسه بجربه",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 6,
    name: "حسام عادل",
    date: "12/04/2026",
    text: "تمام",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 7,
    name: "مروان أشرف",
    date: "30/04/2026",
    text: "استخدمته مرة، والموضوع كان أبسط مما كنت متوقع",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 8,
    name: "كريم ربيع",
    date: "18/05/2026",
    text: "مقبول بالنسبة لي",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 9,
    name: "شريف عاطف",
    date: "07/06/2026",
    text: "فرق معايا عن منتج كنت مستخدمه قبل كده",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 10,
    name: "طارق مجدي",
    date: "21/06/2026",
    text: "أكتر حاجة عجبتني إن التجربة مكنتش محتاجة مني حسابات كتير في الوقت",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 11,
    name: "وليد سامح",
    date: "15/07/2026",
    text: "مش بطال",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 12,
    name: "إسلام رجب",
    date: "04/08/2026",
    text: "من أول تجربة حسيت إنه أقرب لاحتياجي",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 13,
    name: "حازم نبيل",
    date: "19/08/2026",
    text: "هفكر أطلبه تاني",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
];

const ARCHIVE_05: Review[] = [
  {
    id: 1,
    name: "سارة أحمد",
    date: "14/01/2026",
    text: "عجبني",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 2,
    name: "منى خالد",
    date: "05/02/2026",
    text: "جربته بهدوء، والانطباع الأول كويس",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 3,
    name: "نورهان سامي",
    date: "22/03/2026",
    text: "أنا كنت مترددة في البداية، لكن التجربة طلعت أريح مما توقعت",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 4,
    name: "مي محمود",
    date: "13/04/2026",
    text: "مناسب لروتيني",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 5,
    name: "هبة علي",
    date: "27/05/2026",
    text: "لسه في مرحلة التجربة",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 6,
    name: "دينا حسن",
    date: "16/06/2026",
    text: "حبيت إن الموضوع بسيط ومش محتاج تعقيد في الاستخدام",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 7,
    name: "ريم محمد",
    date: "09/07/2026",
    text: "بصراحة ارتحت له",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 8,
    name: "ياسمين عادل",
    date: "02/08/2026",
    text: "مش عندي ملاحظة سلبية لحد دلوقتي",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 9,
    name: "سلمى أشرف",
    date: "18/08/2026",
    text: "التجربة خلتني أفكر أستخدمه مرة تانية",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
];

const ARCHIVE_06: Review[] = [
  {
    id: 1,
    name: "محمود سعيد",
    date: "25/01/2026",
    text: "معروف ومجرب",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 2,
    name: "حسام محمد",
    date: "14/03/2026",
    text: "المرة الأولى كانت كويسة بالنسبة لي",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 3,
    name: "أحمد فوزي",
    date: "29/04/2026",
    text: "كنت عايز أجرب النوع ده تحديدًا، وانطباعي بعد التجربة كان إيجابي",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 4,
    name: "شادي حسن",
    date: "17/05/2026",
    text: "تمام",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 5,
    name: "عمر سامح",
    date: "23/06/2026",
    text: "لسه بجرب وأكوّن رأيي",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 6,
    name: "طارق أحمد",
    date: "12/08/2026",
    text: "بصراحة التجربة كانت مرضية بالنسبة لي",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
];

const ARCHIVE_07: Review[] = [
  {
    id: 1,
    name: "أحمد حمدي",
    date: "04/01/2026",
    text: "الطعم حلو جدًا",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 2,
    name: "محمد سامي",
    date: "18/01/2026",
    text: "الكرز خفيف ومش مزعج",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 3,
    name: "كريم عادل",
    date: "07/02/2026",
    text: "كنت خايف يكون طعمه تقيل، لكن بالعكس قدرت آخده بسهولة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 4,
    name: "رامي حسن",
    date: "26/02/2026",
    text: "حبيت النكهة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 5,
    name: "خالد محمود",
    date: "15/03/2026",
    text: "مش بطال خالص",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 6,
    name: "إيهاب سامح",
    date: "03/04/2026",
    text: "أنا شخصيًا أهم حاجة عندي في النوع ده الطعم، ودي نقطة عجبتني هنا",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 7,
    name: "وليد أحمد",
    date: "24/04/2026",
    text: "سهل وسريع",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 8,
    name: "شريف علي",
    date: "10/05/2026",
    text: "مقبول جدًا من ناحية النكهة",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 9,
    name: "مروان سيد",
    date: "28/05/2026",
    text: "الطعم خلاني أفضل النوع ده عن حاجات جربتها قبل كده",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 10,
    name: "عمر إبراهيم",
    date: "14/06/2026",
    text: "الكرز مدي طعم لطيف ومش قوي زيادة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 11,
    name: "حسن رجب",
    date: "01/07/2026",
    text: "تجربة لطيفة",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 12,
    name: "مصطفى حسن",
    date: "19/07/2026",
    text: "ممكن أجيبه تاني عشان الطعم قبل أي حاجة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 13,
    name: "سامح فؤاد",
    date: "06/08/2026",
    text: "النكهة حلوة فعلًا",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 14,
    name: "عادل نبيل",
    date: "17/08/2026",
    text: "كنت متوقع حاجة مختلفة، لكن طلع أحسن في الطعم مما توقعت",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 15,
    name: "ياسر محمود",
    date: "29/08/2026",
    text: "ده من الأنواع اللي قدرت أتقبل طعمها من غير مشكلة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
];

const ARCHIVE_08: Review[] = [
  {
    id: 1,
    name: "رامي عادل",
    date: "09/01/2026",
    text: "حلو جدًا",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 2,
    name: "محمد فؤاد",
    date: "21/02/2026",
    text: "طعمه مقبول",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 3,
    name: "حسام علي",
    date: "13/03/2026",
    text: "استخدمته في يوم طويل، وكان مناسب بالنسبة لي",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 4,
    name: "أحمد خالد",
    date: "05/04/2026",
    text: "تمام",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 5,
    name: "محمود حسن",
    date: "17/05/2026",
    text: "مش بطال",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 6,
    name: "كريم طارق",
    date: "28/06/2026",
    text: "أكتر حاجة عجبتني إنه سهل في الاستخدام ومش محتاج تحضير",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 7,
    name: "إسلام عادل",
    date: "11/07/2026",
    text: "الطعم أحسن مما توقعت",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 8,
    name: "شريف سامي",
    date: "03/08/2026",
    text: "لسه بجربه لكن البداية كويسة",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 9,
    name: "مروان نبيل",
    date: "16/08/2026",
    text: "حسيته عملي جدًا، خصوصًا لما أكون مستعجل",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 10,
    name: "طارق حسن",
    date: "30/08/2026",
    text: "ممكن أكرره تاني",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
];

const ARCHIVE_09: Review[] = [
  {
    id: 1,
    name: "أحمد سامح",
    date: "06/01/2026",
    text: "خفيف ومريح",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 2,
    name: "محمد عادل",
    date: "27/01/2026",
    text: "أول حاجة لاحظتها إن القوام مش تقيل زي أنواع تانية",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 3,
    name: "كريم محمود",
    date: "14/02/2026",
    text: "بيتحط بسهولة ومش بيفضل إحساس مزعج",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 4,
    name: "عمر حسن",
    date: "08/03/2026",
    text: "الملمس مناسب جدًا",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 5,
    name: "رامي فوزي",
    date: "22/04/2026",
    text: "كويس لحد دلوقتي",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 6,
    name: "محمود سامي",
    date: "11/05/2026",
    text: "كنت بدور تحديدًا على جل يكون سهل في الاستخدام، وده حقق النقطة دي بالنسبة لي",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 7,
    name: "خالد أحمد",
    date: "29/05/2026",
    text: "مش لزج زيادة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 8,
    name: "شادي عادل",
    date: "18/06/2026",
    text: "مفيش ملاحظات سلبية عندي لحد الآن",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 9,
    name: "إيهاب محمد",
    date: "07/07/2026",
    text: "القوام بالنسبة لي أحسن حاجة فيه",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 10,
    name: "حسام رجب",
    date: "23/07/2026",
    text: "استخدامه بسيط ومريح",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 11,
    name: "وليد حسن",
    date: "09/08/2026",
    text: "مقبول",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 12,
    name: "طارق سامح",
    date: "26/08/2026",
    text: "بعد أكتر من مرة استخدام، لسه نفس الانطباع الأول عندي: خفيف وسهل",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
];

const ARCHIVE_10: Review[] = [
  {
    id: 1,
    name: "سارة محمود",
    date: "10/01/2026",
    text: "عجبني",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 2,
    name: "منة أحمد",
    date: "24/01/2026",
    text: "التجربة الأولى كانت كويسة",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 3,
    name: "نور علي",
    date: "12/02/2026",
    text: "أنا جربته لأول مرة وكنت مترددة، لكن بصراحة ارتحت للتجربة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 4,
    name: "ياسمين حسن",
    date: "03/03/2026",
    text: "تمام",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 5,
    name: "هند سامي",
    date: "19/03/2026",
    text: "لسه بجربه",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 6,
    name: "ريم عادل",
    date: "07/04/2026",
    text: "بالنسبة لي كان استخدامه بسيط ومش معقد",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 7,
    name: "دينا محمود",
    date: "26/04/2026",
    text: "حسيته مناسب ليا",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 8,
    name: "مريم خالد",
    date: "15/05/2026",
    text: "مقبول جدًا",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 9,
    name: "ملك أحمد",
    date: "02/06/2026",
    text: "أنا حبيت التجربة، خصوصًا إني كنت داخلة من غير توقعات كبيرة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 10,
    name: "فرح محمد",
    date: "21/06/2026",
    text: "كويس جدًا",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 11,
    name: "هاجر علي",
    date: "08/07/2026",
    text: "الانطباع المبدئي عندي إيجابي",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 12,
    name: "جنى حسن",
    date: "24/07/2026",
    text: "جربته أكتر من مرة، وبالنسبة لي التجربة كانت مريحة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 13,
    name: "بسمة سامح",
    date: "13/08/2026",
    text: "مناسب ليا",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 14,
    name: "آية محمود",
    date: "28/08/2026",
    text: "هكمل تجربتي وأشوف",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
];

const ARCHIVE_11: Review[] = [
  {
    id: 1,
    name: "سلمى أحمد",
    date: "31/01/2026",
    text: "تجربة كويسة",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 2,
    name: "نورهان علي",
    date: "16/03/2026",
    text: "بالنسبة لي التجربة كانت حلوه اوى وممكن أجربه مرة تانية",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 3,
    name: "مي خالد",
    date: "28/04/2026",
    text: "كنت مترددة في البداية، لكن بعد التجربة كان انطباعي أفضل مما توقعت",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 4,
    name: "داليا حسن",
    date: "19/06/2026",
    text: "تمام",
    rating: 5,
    helpful: 0,
    fixedDate: true,
  },
  {
    id: 5,
    name: "هبة سامي",
    date: "22/08/2026",
    text: "لحد دلوقتي مناسب بالنسبة لي",
    rating: 4,
    helpful: 0,
    fixedDate: true,
  },
];

const ARCHIVED_REVIEWS_BY_PRODUCT: Record<string, Review[]> = {
  "vitamax-doubleshot-energy-honey": VITAMAX_REVIEWS,
  "cialis-tadalafil-20mg-30-tablets": ARCHIVE_01,
  "royal-cream": ARCHIVE_02,
  "hard-on-sildenafil-130mg-dapoxetine-60mg": ARCHIVE_03,
  "power-36-power-control-for-36-hours": ARCHIVE_04,
  "lovezone-intimacy-at-its-peak-10x400mg": ARCHIVE_05,
  "viagra-pfizer-100mg": ARCHIVE_06,
  "dal-el-khair-honey-cherry": ARCHIVE_07,
  "top-sellers-honey": ARCHIVE_08,
  "halpeno-men-gel-50gm": ARCHIVE_09,
  "lovezone-intimacy-at-its-peak-10x380mg": ARCHIVE_10,
  "viagra-20-tablets": ARCHIVE_11,
};

interface ProductReviewsResult {
  reviews: Review[];
  rating: number;
  reviewCount: number;
}

/**
 * يرجع تقييمات فريدة وثابتة لمنتج معيّن.
 * - الاختيار حتمي (نفس slug → نفس النتيجة دائماً) ويعتمد على slug المنتج،
 *   فيختلف المنتج عن الآخر.
 * - `reviewCount` يساوي عدد التعليقات المعروضة فعلاً.
 * - `rating` هو متوسط تقييمات التعليقات المعروضة (مطابق للصفحة).
 */
export function getProductReviews(
  slug: string,
  category: ProductCategory,
  maxReviews = 5,
): ProductReviewsResult {
  const archivedProductReviews = ARCHIVED_REVIEWS_BY_PRODUCT[slug];
  if (archivedProductReviews) {
    const selected = archivedProductReviews.slice(
      0,
      Math.min(maxReviews, archivedProductReviews.length),
    );
    const rating =
      Math.round(
        (selected.reduce((sum, review) => sum + review.rating, 0) / selected.length) * 10,
      ) / 10;
    return { reviews: selected, rating, reviewCount: selected.length };
  }

  const categoryPool =
    category === "women" ? WOMEN_REVIEWS : category === "devices" ? DEVICE_REVIEWS : MEN_REVIEWS;
  // كريفا لديه 73 تقييماً تاريخياً مكتمل النجوم؛ نعرض خمس شهادات 5/5 ثابتة.
  const pool =
    slug === "kreva-gel-for-men"
      ? categoryPool.filter((review) => review.rating === 5)
      : categoryPool;

  const seed = hashCode(slug || "default");
  const rand = mulberry32(seed);

  // اختر عدداً بين 4 و maxReviews تقييمات (لكن لا يتجاوز حجم المجموعة)
  const max = Math.min(maxReviews, pool.length);
  const count =
    slug === "kreva-gel-for-men"
      ? max
      : Math.max(3, Math.min(max, 3 + Math.floor(rand() * (max - 2))));

  // خلط حتمي للمجموعة (Fisher-Yates بمولّد seeded) ثم أخذ أول count عناصر
  const arr = [...pool];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  const selected = arr.slice(0, count);

  const rating =
    Math.round((selected.reduce((s, r) => s + r.rating, 0) / selected.length) * 10) / 10;

  return { reviews: selected, rating, reviewCount: selected.length };
}
