/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EducationRouteImport } from './routes/education'
import { Route as MedicalReviewBoardRouteImport } from './routes/medical-review-board'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as EducationSlugRouteImport } from './routes/education_.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ProductsDevicesRouteImport } from './routes/products.devices'
import { Route as ProductsMenRouteImport } from './routes/products.men'
import { Route as ProductsWomenRouteImport } from './routes/products.women'
import { Route as ProductsGuidesSlugRouteImport } from './routes/products.guides.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalReviewBoardRoute = MedicalReviewBoardRouteImport.update({
  id: '/medical-review-board',
  path: '/medical-review-board',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationSlugRoute = EducationSlugRouteImport.update({
  id: '/education_/$slug',
  path: '/education/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsDevicesRoute = ProductsDevicesRouteImport.update({
  id: '/products/devices',
  path: '/products/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsMenRoute = ProductsMenRouteImport.update({
  id: '/products/men',
  path: '/products/men',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsWomenRoute = ProductsWomenRouteImport.update({
  id: '/products/women',
  path: '/products/women',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsGuidesSlugRoute = ProductsGuidesSlugRouteImport.update({
  id: '/products/guides/$slug',
  path: '/products/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/medical-review-board': typeof MedicalReviewBoardRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/wishlist': typeof WishlistRoute
  '/education/$slug': typeof EducationSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/devices': typeof ProductsDevicesRoute
  '/products/men': typeof ProductsMenRoute
  '/products/women': typeof ProductsWomenRoute
  '/products/guides/$slug': typeof ProductsGuidesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/medical-review-board': typeof MedicalReviewBoardRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/wishlist': typeof WishlistRoute
  '/education/$slug': typeof EducationSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/devices': typeof ProductsDevicesRoute
  '/products/men': typeof ProductsMenRoute
  '/products/women': typeof ProductsWomenRoute
  '/products/guides/$slug': typeof ProductsGuidesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/medical-review-board': typeof MedicalReviewBoardRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/wishlist': typeof WishlistRoute
  '/education_/$slug': typeof EducationSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/devices': typeof ProductsDevicesRoute
  '/products/men': typeof ProductsMenRoute
  '/products/women': typeof ProductsWomenRoute
  '/products/guides/$slug': typeof ProductsGuidesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/education'
    | '/medical-review-board'
    | '/order-confirmed'
    | '/privacy'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/terms'
    | '/thank-you'
    | '/wishlist'
    | '/education/$slug'
    | '/products/$slug'
    | '/products/devices'
    | '/products/men'
    | '/products/women'
    | '/products/guides/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/education'
    | '/medical-review-board'
    | '/order-confirmed'
    | '/privacy'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/terms'
    | '/thank-you'
    | '/wishlist'
    | '/education/$slug'
    | '/products/$slug'
    | '/products/devices'
    | '/products/men'
    | '/products/women'
    | '/products/guides/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/education'
    | '/medical-review-board'
    | '/order-confirmed'
    | '/privacy'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/terms'
    | '/thank-you'
    | '/wishlist'
    | '/education_/$slug'
    | '/products/$slug'
    | '/products/devices'
    | '/products/men'
    | '/products/women'
    | '/products/guides/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  MedicalReviewBoardRoute: typeof MedicalReviewBoardRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  WishlistRoute: typeof WishlistRoute
  EducationSlugRoute: typeof EducationSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsDevicesRoute: typeof ProductsDevicesRoute
  ProductsMenRoute: typeof ProductsMenRoute
  ProductsWomenRoute: typeof ProductsWomenRoute
  ProductsGuidesSlugRoute: typeof ProductsGuidesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-review-board': {
      id: '/medical-review-board'
      path: '/medical-review-board'
      fullPath: '/medical-review-board'
      preLoaderRoute: typeof MedicalReviewBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education_/$slug': {
      id: '/education_/$slug'
      path: '/education/$slug'
      fullPath: '/education/$slug'
      preLoaderRoute: typeof EducationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/devices': {
      id: '/products/devices'
      path: '/products/devices'
      fullPath: '/products/devices'
      preLoaderRoute: typeof ProductsDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/men': {
      id: '/products/men'
      path: '/products/men'
      fullPath: '/products/men'
      preLoaderRoute: typeof ProductsMenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/women': {
      id: '/products/women'
      path: '/products/women'
      fullPath: '/products/women'
      preLoaderRoute: typeof ProductsWomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/guides/$slug': {
      id: '/products/guides/$slug'
      path: '/products/guides/$slug'
      fullPath: '/products/guides/$slug'
      preLoaderRoute: typeof ProductsGuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  MedicalReviewBoardRoute: MedicalReviewBoardRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  WishlistRoute: WishlistRoute,
  EducationSlugRoute: EducationSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsDevicesRoute: ProductsDevicesRoute,
  ProductsMenRoute: ProductsMenRoute,
  ProductsWomenRoute: ProductsWomenRoute,
  ProductsGuidesSlugRoute: ProductsGuidesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
