/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsWomenRouteImport } from './routes/products.women'
import { Route as ProductsMenRouteImport } from './routes/products.men'
import { Route as ProductsDevicesRouteImport } from './routes/products.devices'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as EducationSlugRouteImport } from './routes/education_.$slug'

const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsWomenRoute = ProductsWomenRouteImport.update({
  id: '/products/women',
  path: '/products/women',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsMenRoute = ProductsMenRouteImport.update({
  id: '/products/men',
  path: '/products/men',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsDevicesRoute = ProductsDevicesRouteImport.update({
  id: '/products/devices',
  path: '/products/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationSlugRoute = EducationSlugRouteImport.update({
  id: '/education_/$slug',
  path: '/education/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/wholesale': typeof WholesaleRoute
  '/education/$slug': typeof EducationSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/devices': typeof ProductsDevicesRoute
  '/products/men': typeof ProductsMenRoute
  '/products/women': typeof ProductsWomenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/wholesale': typeof WholesaleRoute
  '/education/$slug': typeof EducationSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/devices': typeof ProductsDevicesRoute
  '/products/men': typeof ProductsMenRoute
  '/products/women': typeof ProductsWomenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/wholesale': typeof WholesaleRoute
  '/education_/$slug': typeof EducationSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/devices': typeof ProductsDevicesRoute
  '/products/men': typeof ProductsMenRoute
  '/products/women': typeof ProductsWomenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/education'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/terms'
    | '/thank-you'
    | '/wholesale'
    | '/education/$slug'
    | '/products/$id'
    | '/products/devices'
    | '/products/men'
    | '/products/women'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/education'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/terms'
    | '/thank-you'
    | '/wholesale'
    | '/education/$slug'
    | '/products/$id'
    | '/products/devices'
    | '/products/men'
    | '/products/women'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/education'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/terms'
    | '/thank-you'
    | '/wholesale'
    | '/education_/$slug'
    | '/products/$id'
    | '/products/devices'
    | '/products/men'
    | '/products/women'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  WholesaleRoute: typeof WholesaleRoute
  EducationSlugRoute: typeof EducationSlugRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsDevicesRoute: typeof ProductsDevicesRoute
  ProductsMenRoute: typeof ProductsMenRoute
  ProductsWomenRoute: typeof ProductsWomenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/women': {
      id: '/products/women'
      path: '/products/women'
      fullPath: '/products/women'
      preLoaderRoute: typeof ProductsWomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/men': {
      id: '/products/men'
      path: '/products/men'
      fullPath: '/products/men'
      preLoaderRoute: typeof ProductsMenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/devices': {
      id: '/products/devices'
      path: '/products/devices'
      fullPath: '/products/devices'
      preLoaderRoute: typeof ProductsDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education_/$slug': {
      id: '/education_/$slug'
      path: '/education/$slug'
      fullPath: '/education/$slug'
      preLoaderRoute: typeof EducationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  WholesaleRoute: WholesaleRoute,
  EducationSlugRoute: EducationSlugRoute,
  ProductsIdRoute: ProductsIdRoute,
  ProductsDevicesRoute: ProductsDevicesRoute,
  ProductsMenRoute: ProductsMenRoute,
  ProductsWomenRoute: ProductsWomenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
